const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{"8Direções": 0},
	{Jogador: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{TiroJogador: 0},
	{Mouse: 0},
	{Esmaecer: 0},
	{Explosao: 0},
	{VIda: 0},
	{Inimigo: 0},
	{Âncora: 0},
	{Pontuação: 0},
	{GameOver: 0},
	{Teclado: 0},
	{Inicio: 0},
	{GameOverTela: 0},
	{Iniciar: 0},
	{Reiniciar: 0},
	{BotãoInicio: 0},
	{Áudio: 0},
	{pontos: 0},
	{PontosGameOver: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Jogador: class extends self.ISpriteInstance {},
	TiroJogador: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Explosao: class extends self.ISpriteInstance {},
	Inimigo: class extends self.ISpriteInstance {},
	Pontuação: class extends self.ITextInstance {},
	GameOver: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	Inicio: class extends self.ISpriteInstance {},
	GameOverTela: class extends self.ISpriteInstance {},
	Iniciar: class extends self.ISpriteInstance {},
	Reiniciar: class extends self.ISpriteInstance {},
	BotãoInicio: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {}
}